name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Se le hace Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Paso 2: Se elecciona el JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Paso 3:Dependencias de  Cache Maven 
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Paso 4: Run Maven build
      - name: Build with Maven
        run: mvn clean install
      
      # Paso 5: Guardar Jar
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Guardar Jar
          path: target/*.jar

